version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - websocket

  websocket:
    image: php:7.4-cli
    volumes:
      - ./src:/app
    working_dir: /app
    command: php chat-server.php
    ports:
      -  "8080:8080"
